### ISSUE TITLE
Pod goes int CrashLoopBackOff status when enable exporter in citrix-k8s-ingress-controller

### ISSUE THREAD

**Issue by LipingMao** [citrix/citrix-k8s-ingress-controller#10]
quay.io/citrix/netscaler-metrics-exporter:v1.0.0 consistent restarting when I enable exporter.

Here is the command I'm using the following helm command:
helm install citrix-k8s-ingress-controller --name vpx --set license.accept=yes,ingressClass[0]=vpx,exporter.require=1.0 --set nsIP=10.253.3.64

The pod goes into CrashLoopBackOff status:
[root@ams-dev-limao-ctrl001 stable]# kubectl describe pod cic-k8s-ingress-controller
Name:               cic-k8s-ingress-controller
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               ams-dev-limao-work002/10.253.111.137
Start Time:         Tue, 26 Mar 2019 08:27:58 +0000
Labels:             app=cic-k8s-ingress-controller
Annotations:        <none>
Status:             Running
IP:                 10.1.5.8
Containers:
  cic-k8s-ingress-controller:
    Container ID:  docker://5c9a1d91c39425375d11f83c623ac9aaed9d4174b386a10eb2beb36aa56f89c9
    Image:         quay.io/citrix/citrix-k8s-ingress-controller:1.1.1
    Image ID:      docker-pullable://quay.io/citrix/citrix-k8s-ingress-controller@sha256:61b747330c83f4fe241476a55de8cb02c7078af664e1370ccd957d797182af64
    Port:          <none>
    Host Port:     <none>
    Args:
      --ingress-class vpx
    State:          Running
      Started:      Tue, 26 Mar 2019 08:28:00 +0000
    Ready:          True
    Restart Count:  0
    Environment:
      NS_IP:        10.253.3.64
      NS_USER:      <set to the key 'username' in secret 'nslogin1'>  Optional: false
      NS_PASSWORD:  <set to the key 'password' in secret 'nslogin1'>  Optional: false
      EULA:         yes
      LOGLEVEL:     DEBUG
      NS_PROTOCOL:  HTTPS
      NS_PORT:      443
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from cic-k8s-role-token-svkdq (ro)
  exp:
    Container ID:  docker://5a0d72ac300d8db99843f849f74f9b522f307f4409681d57a851c4f35468a6ec
    Image:         quay.io/citrix/netscaler-metrics-exporter:v1.0.0
    Image ID:      docker-pullable://quay.io/citrix/netscaler-metrics-exporter@sha256:2cc760acf629794836ec8e7aaa057c1494b7c7e05caee6b596fffb182d3f090e
    Port:          <none>
    Host Port:     <none>
    Args:
      --target-nsip=10.253.3.64
      --port=8888
    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 26 Mar 2019 08:28:42 +0000
      Finished:     Tue, 26 Mar 2019 08:28:52 +0000
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 26 Mar 2019 08:28:14 +0000
      Finished:     Tue, 26 Mar 2019 08:28:24 +0000
    Ready:          False
    Restart Count:  2
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from cic-k8s-role-token-svkdq (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  cic-k8s-role-token-svkdq:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  cic-k8s-role-token-svkdq
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                From                            Message
  ----     ------     ----               ----                            -------
  Normal   Scheduled  65s                default-scheduler               Successfully assigned default/cic-k8s-ingress-controller to ams-dev-limao-work002
  Normal   Pulling    64s                kubelet, ams-dev-limao-work002  pulling image "quay.io/citrix/citrix-k8s-ingress-controller:1.1.1"
  Normal   Pulled     63s                kubelet, ams-dev-limao-work002  Successfully pulled image "quay.io/citrix/citrix-k8s-ingress-controller:1.1.1"
  Normal   Created    63s                kubelet, ams-dev-limao-work002  Created container
  Normal   Started    63s                kubelet, ams-dev-limao-work002  Started container
  Normal   Pulling    23s (x3 over 63s)  kubelet, ams-dev-limao-work002  pulling image "quay.io/citrix/netscaler-metrics-exporter:v1.0.0"
  Normal   Pulled     22s (x3 over 61s)  kubelet, ams-dev-limao-work002  Successfully pulled image "quay.io/citrix/netscaler-metrics-exporter:v1.0.0"
  Normal   Created    22s (x3 over 61s)  kubelet, ams-dev-limao-work002  Created container
  Normal   Started    21s (x3 over 61s)  kubelet, ams-dev-limao-work002  Started container
  Warning  BackOff    10s (x2 over 38s)  kubelet, ams-dev-limao-work002  Back-off restarting failed container
[root@ams-dev-limao-ctrl001 stable]# kubectl get pods
NAME                         READY   STATUS             RESTARTS   AGE
cic-k8s-ingress-controller   1/2     CrashLoopBackOff   2          73s

**Comment by krdpk17** [comment]
Thanks for reaching us and notifying this issue. Can you please share the log of container.
You can use 'kubectl logs -f cic-k8s-ingress-controller -c exp'

**Comment by janraj** [comment]
@LipingMao , Can you please try with "latest" tag instead of  "v1.0.0"

**Comment by LipingMao** [comment]
Thanks @krdpk17 , here it is:
[root@ams-dev-limao-ctrl001 ~]# kubectl logs -f cic-k8s-ingress-controller -c exp -n vpx
>>> Sleeping for: 10 seconds ...
>>> Starting the exporter on port: 8888
>>> Registering collector for: ['10.253.3.64']
>>> Collecting stats for: 10.253.3.64::protocoltcp
>>> Collecting stats for: 10.253.3.64::service
>>> Collecting stats for: 10.253.3.64::csvserver
>>> Collecting stats for: 10.253.3.64::Interface
>>> Collecting stats for: 10.253.3.64::system
>>> Collecting stats for: 10.253.3.64::protocolhttp
>>> Collecting stats for: 10.253.3.64::ssl
>>> Collecting stats for: 10.253.3.64::services
>>> Caught exception while collecting data: local variable 'servicegroup_data' referenced before assignment
>>> Collecting stats for: 10.253.3.64::lbvserver
>>> Collecting stats for: 10.253.3.64::protocolip
>>> Caught exception while adding counter tcptotrxpkts to protocoltcp: 'NoneType' object has no attribute '__getitem__'
>>> Caught exception while adding counter tcptotrxbytes to protocoltcp: 'NoneType' object has no attribute '__getitem__'
>>> Caught exception while adding counter tcptottxbytes to protocoltcp: 'NoneType' object has no attribute '__getitem__'
>>> Caught exception while adding counter tcptottxpkts to protocoltcp: 'NoneType' object has no attribute '__getitem__'
>>> Caught exception while adding counter tcptotclientconnopened to protocoltcp: 'NoneType' object has no attribute '__getitem__'
>>> Caught exception while adding counter tcptotserverconnopened to protocoltcp: 'NoneType' object has no attribute '__getitem__'
>>> Caught exception while adding counter tcptotsyn to protocoltcp: 'NoneType' object has no attribute '__getitem__'
>>> Caught exception while adding counter tcptotsynprobe to protocoltcp: 'NoneType' object has no attribute '__getitem__'
>>> Caught exception while adding counter tcptotsvrfin to protocoltcp: 'NoneType' object has no attribute '__getitem__'
>>> Caught exception while adding counter tcptotcltfin to protocoltcp: 'NoneType' object has no attribute '__getitem__'
>>> Caught exception while adding guage tcpactiveserverconn to protocoltcp: 'NoneType' object has no attribute '__getitem__'
>>> Caught exception while adding guage tcpcurclientconnestablished to protocoltcp: 'NoneType' object has no attribute '__getitem__'
>>> Caught exception while adding guage tcpcurserverconnestablished to protocoltcp: 'NoneType' object has no attribute '__getitem__'
>>> Caught exception while adding guage tcprxpktsrate to protocoltcp: 'NoneType' object has no attribute '__getitem__'
>>> Caught exception while adding guage tcptxpktsrate to protocoltcp: 'NoneType' object has no attribute '__getitem__'
>>> Caught exception while adding guage tcptxbytesrate to protocoltcp: 'NoneType' object has no attribute '__getitem__'
>>> Caught exception while adding guage tcpclientconnopenedrate to protocoltcp: 'NoneType' object has no attribute '__getitem__'
>>> Caught exception while adding guage tcperrbadchecksum to protocoltcp: 'NoneType' object has no attribute '__getitem__'
>>> Caught exception while adding guage tcperrbadchecksumrate to protocoltcp: 'NoneType' object has no attribute '__getitem__'
>>> Caught exception while adding guage tcperranyportfail to protocoltcp: 'NoneType' object has no attribute '__getitem__'
>>> Caught exception while adding guage tcperripportfail to protocoltcp: 'NoneType' object has no attribute '__getitem__'
>>> Caught exception while adding guage tcperrbadstateconn to protocoltcp: 'NoneType' object has no attribute '__getitem__'
>>> Caught exception while adding guage tcperrrstthreshold to protocoltcp: 'NoneType' object has no attribute '__getitem__'
>>> Caught exception while adding guage tcpsynrate to protocoltcp: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/exporter/exporter.py", line 156, in <module>
>>> Caught exception while adding guage tcpsynproberate to protocoltcp: 'NoneType' object has no attribute '__getitem__'
    REGISTRY.register(NetscalerCollector(nsips=args.target_nsip, metrics=metrics_json, username=ns_user, password=ns_password, secure=args.secure.lower()))
  File "/usr/lib/python2.7/site-packages/prometheus_client/core.py", line 96, in register
    names = self._get_names(collector)
  File "/usr/lib/python2.7/site-packages/prometheus_client/core.py", line 136, in _get_names
    for metric in desc_func():
  File "/exporter/exporter.py", line 93, in collect
    label_values = [data_item[key] for key in [v[0] for v in entity['labels']]]
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by LipingMao** [comment]
@janraj :  it works the container did not crash, but I see the following log:

Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 868, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 741, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not enough arguments for format string
Logged from file exporter.py, line 189
error: unexpected EOF

**Comment by krdpk17** [comment]
@LipingMao We have updated exporter. We are bringing some more changes related to user credential error condition. Meanwhile, you can try with current version of exporter.

**Comment by krdpk17** [comment]
@LipingMao  Thanks for providing data and reporting this issue.
We have updated exporter. We are bringing some more changes related to user credential error condition. Meanwhile, you can try with current version of exporter.

**Comment by haroraCitrix** [comment]
@LipingMao we have updated the exporter version to v1.0.5, you can try with the latest cpx+exporter. we have fixed this issue. closing for now.
