### ISSUE TITLE
readme.md ambiguity 

### ISSUE THREAD

**Issue by Nacho-Leon** [citrix/citrix-k8s-ingress-controller#2]
Choose the deployment
1. Bring up Citrix Ingress Controller for VPX, MPX
...
 **kubectl create -f guestbook-ingress.yml**

2. Bring up CPX with builtin Controller

...
 **kubectl create -f guestbook-ingress.yml**

SAME YAML FILE

**Comment by janraj** [comment]
@Nacho-Leon    
              Example talks about bringing up guest book application  which will be load balanced by either VPX/MPX or  CPX-wth built in controller. The yaml file mentioned here is for ingress resource which is same for both deployment models.  Deployment section has details about two models of deployment  where separate yamls being used.

**Comment by janraj** [comment]
Had updated the Doc. CLosing this issue.
