### ISSUE TITLE
Do not support "-" in the rewritepolicy name definition

### ISSUE THREAD

**Issue by vsavostyanov** [citrix/citrix-k8s-ingress-controller#220]
When i use "-" symbol in rewritepolicy name definition, i've got the following error:
ERROR - [rewritepolicy.py:validate_add:179] (MainThread) CRD name nexus-sonatype-nexus can't contain "-"
The "-" symbol use by default in all helm charts

**Comment by Saravanakumar2016** [comment]
We do not support '-' within the rewrite CRD policy name, due to Citrix ADC incapability of not supporting '-' in its policy names

Also, please help in providing the helm chart links which uses hyphen '-' as an option. We can help in providing a solution for the helm chart issues
