### ISSUE TITLE
Broken link in readme

### ISSUE THREAD

**Issue by andreasottosson** [citrix/citrix-k8s-ingress-controller#243]
The link to your Slack channel in the repo is broken.

Citrix ADC Cloud Native Slack channel [https://github.com/citrix/citrix-k8s-ingress-controller/blob/master/citrixadccloudnative.slack.com]

should be

Citrix ADC Cloud Native Slack channel [https://citrixadccloudnative.slack.com]

/Andreas

**Comment by kpsmuthu** [comment]
Hi, Thanks. Fixed it now.
