### ISSUE TITLE
Policy and VServer name length limitation (127 characters)

### ISSUE THREAD

**Issue by cbunix** [citrix/citrix-k8s-ingress-controller#262]
**Is your feature request related to a problem? Please describe.**
Yes, in our k8s environment we exceed always the name limitations of 127 characters for policy names and vservers, because ingress controller is settings it's name depending on the service name, etc. in k8s.
eg.: k8scadev-prometheus-operator-alertmanager_infra-monitoring_80_k8scadev-prometheus-operator-alertmanager_infra-monitoring_9093_svc

**Describe the solution you'd like**
increase the names to 256 characters

**Describe alternatives you've considered**
 change the name concept in ingress controller

**Additional context**
cic-k8s-ingress-deployment-ns-k8scaaspdev-64f99b4c56-zprh6
cic-k8s-ingress-controller-ns-k8scaaspdev INFO:docker_netscaler:Priority
fetched 200000208 for VS: k8scadev-10.16.80.153_80_http and rule:
HTTP.REQ.HOSTNAME.SERVER.EQ("alertmanager.dev.viollier.ch") &&
HTTP.REQ.URL.PATH.SET_TEXT_MODE(IGNORECASE).STARTSWITH("/")
cic-k8s-ingress-deployment-ns-k8scaaspdev-64f99b4c56-zprh6
cic-k8s-ingress-controller-ns-k8scaaspdev 2020-06-19 12:26:16,958  -
ERROR - [nitrointerface.py:_bind_cs_vserver_res_policy:2851]
(MainThread) Nitro
Exception::bind_cs_vserver_res_policy::errorcode=1106,message=String
length exceeds maximum [policyName, 127]
cic-k8s-ingress-deployment-ns-k8scaaspdev-64f99b4c56-zprh6
cic-k8s-ingress-controller-ns-k8scaaspdev ERROR:docker_netscaler:Nitro
Exception::bind_cs_vserver_res_policy::errorcode=1106,message=String
length exceeds maximum [policyName, 127]
cic-k8s-ingress-deployment-ns-k8scaaspdev-64f99b4c56-zprh6
cic-k8s-ingress-controller-ns-k8scaaspdev 2020-06-19 12:26:16,959  -
DEBUG - [nitrointerface.py:_configure_policy_in_cs_vs:3101] (MainThread)
RESPONDER_POLICY: Finished processing responder policy
k8scadev-prometheus-operator-alertmanager_infra-monitoring_80_k8scadev-prometheus-operator-alertmanager_infra-monitoring_9093_svc[{'type':
'redirect', 'target': '"https://" + http.req.HOSTNAME.SERVER + ":" +
"443" + http.req.url', 'rule':
u'HTTP.REQ.HOSTNAME.SERVER.EQ("alertmanager.dev.viollier.ch") &&
HTTP.REQ.URL.PATH.SET_TEXT_MODE(IGNORECASE).STARTSWITH("/")'}]
configuration to App
k8scadev-prometheus-operator-alertmanager_infra-monitoring_80

**Comment by matthyx** [comment]
Maybe the ingress controller should shorten the name if it exceeds a limit on the netscaler side?

**Comment by kumar-swamy** [comment]
Recent releases have addressed this issue.

**Comment by chiradeep** [comment]
fixed in https://github.com/citrix/citrix-k8s-ingress-controller/releases/tag/1.12.2

**Comment by matthyx** [comment]
Thanks for the update @chiradeep and @kumar-swamy so I guess this issue can be closed?

**Comment by chiradeep** [comment]
Yes, will close.
