### ISSUE TITLE
JSON logs for CIC

### ISSUE THREAD

**Issue by andy812** [citrix/citrix-k8s-ingress-controller#337]
Many companies use Elasticsearch/Logstash/Kibana to store and query logs. If CIC logs will be in JSON, it will be much more easier to collect and parse them, because JSON data is structured.

Please, add support of JSON stdout/stderr logs.

**Comment by ankits123** [comment]
Thanks for the enhancment.We have discussed it internally.
We are tracking it.

**Comment by mayurmohanpatil** [comment]
Hello @andy812,
Will you please provide your contact details on AppModernization@citrite.net
We would like to assist you further for your use case.

Regards,
Mayur

**Comment by apoorva-05** [comment]
@andy812 This is supported in CIC 1.23.10+.  "JSONLOG" can be set to true, either via env variable or configmap.
https://github.com/citrix/citrix-k8s-ingress-controller/releases/tag/1.23.10. 
Closing this issue.

**Comment by apoorva-05** [comment]
@andy812 This is supported in CIC 1.23.10+.  "JSONLOG" can be set to true, either via env variable or configmap.
https://github.com/citrix/citrix-k8s-ingress-controller/releases/tag/1.23.10. 
Closing this issue.
