### ISSUE TITLE
Steps of manually created route got null value in podNetwork and incorrect podNetwork subnet masks appended to gateway IP

### ISSUE THREAD

**Issue by raphael1688** [citrix/citrix-k8s-ingress-controller#351]
**Describe the bug**
No value returned in podNetwork and the wrong subnet mask as we use CNI Calico.

**To Reproduce**
1. Steps: 
`# kubectl get nodes -o jsonpath="{range .items[*]}{'podNetwork: '}{.metadata.annotations.projectcalico\.org/IPv4IPIPTunnelAddr}{'\tgateway: '}{.metadata.annotations.projectcalico\.org/IPv4Address}{'\n'}"`

https://github.com/citrix/citrix-k8s-ingress-controller/blob/master/docs/network/staticrouting.md#manually-configure-route-on-the-citrix-adc-instance

2. Version of the Citrix Ingress Controller: 1.11.3
3. Version of MPX/VPX/CPX: 13.0 71.40

**Expected behavior**
podNetwork values should be returned with subnet mask.

**Additional context**
Since we followed quick start installation on Calico website, they have change the default overlay protocol from IPinIP to VXLAN, therefore it is expected null value returned.
Besides, podNetwork subnet mask is incorrect and appended to gateway IP.

`# kubectl get nodes -o jsonpath="{range .items[*]}{'podNetwork: '}{.spec.podCIDR}{'\t'}{'gateway: '}{.status.addresses[0].address}{'\n'}{end}"
podNetwork: 10.245.0.0/24	gateway: 172.16.100.81
podNetwork: 10.245.4.0/24	gateway: 172.16.100.82
podNetwork: 10.245.1.0/24	gateway: 172.16.100.83
podNetwork: 10.245.3.0/24	gateway: 172.16.100.84
podNetwork: 10.245.2.0/24	gateway: 172.16.100.85`

`# kubectl get nodes -o jsonpath="{range .items[*]}{'podNetwork: '}{.metadata.annotations.projectcalico\.org/IPv4IPIPTunnelAddr}{'\tgateway: '}{.metadata.annotations.projectcalico\.org/IPv4Address}{'\n'}"
podNetwork: 	gateway: 172.16.100.81/16
podNetwork: 	gateway: 172.16.100.82/16
podNetwork: 	gateway: 172.16.100.83/16
podNetwork: 	gateway: 172.16.100.84/16
podNetwork: 	gateway: 172.16.100.85/16
podNetwork: 	gateway: `
[github-issue-20201214.txt](https://github.com/citrix/citrix-k8s-ingress-controller/files/5686856/github-issue-20201214.txt)

**Comment by kumar-swamy** [comment]
This has been addressed in release 1.13.15.

**Comment by ankits123** [comment]
closing the issue as fixed in 1.13.15.
