### ISSUE TITLE
type array or plural for spec.validation.openAPIV3Schema.properties.spec.properties.vip in listener CRD

### ISSUE THREAD

**Issue by raphael1688** [citrix/citrix-k8s-ingress-controller#354]
**Describe the solution you'd like**

I would like to reduce the amount of ingress objects, because it consumes too much Citrix objects resource for per frontend ip per ingress rule if I need to deploy tens of thousands of cert/key among thousands of vips. 

**Describe alternatives you've considered**
you may have listener crd support multiple vips per listener or let annotation ingress.citrix.com/frontend-ip or service.citrix.com/frontend-ip to accept multiple vip values.

**Additional context**
It will be nicer if vip of listener crd or annotation frondend-ip could use wildcard ip or ip pattern.

**Comment by ankits123** [comment]
Thanks @raphael1688 We will try to look in this enhancement and update.

**Comment by kumar-swamy** [comment]
Listener CRD accepts multiple VIPs as part of ipset. Closing the issue
