### ISSUE TITLE
LB and CS objects prefix

### ISSUE THREAD

**Issue by alloran** [citrix/citrix-k8s-ingress-controller#36]
Hi!

Is there any possibility to configure prefix for LB and CS objects created in citrix mpx by CIC, instead of "k8s" ?

It will help to simplify visual identification of objects created by different CIC instances in different k8s clusters.

**Comment by IKabdyushev** [comment]
We have the same issue, the way of renaming ingresses for different clusters seems to be inefficient

**Comment by janraj** [comment]
@alloran @IKabdyushev , We have an option to control the Prefix. Please use following settings at CIC level to control the prefix of Netscaler COnfigurations. Change the value field with your choice of prefix.
    - name: "NS_APPS_NAME_PREFIX"
       value: "k8s-"

**Comment by janraj** [comment]
@alloran , @IKabdyushev , Please refer README section in deployment/baremetal. 

https://github.com/citrix/citrix-k8s-ingress-controller/tree/master/deployment/baremetal

Please join our slack channel [Question section of Main README], we can provide all the help with Citrix Ingress controller and cpx. 
https://citrixadccloudnative.slack.com/messages/GFPHN10HF/

I am closing this issue, now.
