### ISSUE TITLE
Smart annotation for SSL-Profile not working

### ISSUE THREAD

**Issue by jbSyTech** [citrix/citrix-k8s-ingress-controller#379]
I try to use frontend-sslprofile annotation for an ingress resources but the annotation seams not be honored.

The ingress controller has following settings:
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: citrix
    ingress.citrix.com/frontend-ip: <public frontend ip>
    ingress.citrix.com/insecure-termination: redirect
    ingress.citrix.com/frontend-sslprofile: "ssl_profile_secure_frontend"
spec:
  rules:
  - http: <fqdn>
      paths:
      - backend:
          serviceName: release-name-alfresco-cs-ce-share
          servicePort: 80
        path: /share
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - <fqdn>
    secretName: <secretname>
status:
  loadBalancer: {}

---

When I deploy this ingress ressource in the netscaler VPX there is always the default SSL-policy 'ns_default_ssl_profile_frontend' bound to the CS VS.

On the netscaler itself there is a SSL-profile called 'ssl_profile_secure_frontend' 

I expeceted that SSL-Profile 'ssl_profile_secure_frontend' will be bound to the CS VS

citrix-ingress-controller is version 1.13.15

kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7+k3s1", GitCommit:"5a00e38db4c198fb0725a6b709380aed8053d637", GitTreeState:"clean", BuildDate:"2021-01-14T23:09:21Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7+k3s1", GitCommit:"5a00e38db4c198fb0725a6b709380aed8053d637", GitTreeState:"clean", BuildDate:"2021-01-14T23:09:21Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by kumar-swamy** [comment]
All the frontend profiles are honoured only if specified as part of the frontend-ingress. CIC considers an ingress as a frontend-ingress if spec.rules are not populated. So you need to create another ingress without 'backend' to specify the frontend SSL profile as shown below. 

apiVersion: networking.k8s.io/v1
 kind: Ingress
 metadata:
   name: frontend-ingress
   annotations:
     kubernetes.io/ingress.class: "citrix"
     ingress.citrix.com/frontend-ip: 
     ingress.citrix.com/insecure-termination: redirect
     ingress.citrix.com/frontend-sslprofile: "ssl_profile_secure_frontend"
 spec:
   rules:
   - host:

**Comment by ankits123** [comment]
Closing the issue for now .. If suggested approch doesn't work please re-open the issue.
