### ISSUE TITLE
Incorrect examples and IP in the below doc

### ISSUE THREAD

**Issue by Gururajnrao** [citrix/citrix-k8s-ingress-controller#394]
The section "Expose services of type LoadBalancer with IP addresses assigned by the IPAM controller¶" and the "Expose services of type LoadBalancer by specifying an IP address¶" seem to have conflicting examples. The first one probably need to have "loadBalancerIP: " " (i.e blank) to get allocated through IPAM and second one should have the  explicit IP (as already specified).

Secondly, 110.217.212.16 IP is used but references in the doc is for "10.217.212.16".

Docs URL:https://developer-docs.citrix.com/projects/citrix-k8s-ingress-controller/en/latest/network/type_loadbalancer/

**Comment by sreejithgs** [comment]
This issue is fixed. See the following link:

https://github.com/citrix/citrix-k8s-ingress-controller/blob/master/docs/network/type_loadbalancer.md
