### ISSUE TITLE
Using Ingress Controller with NetScaler INC

### ISSUE THREAD

**Issue by simongottschlag** [citrix/citrix-k8s-ingress-controller#4]
Hi,

Reading the YAML for the ingress controller, there isn’t any info about how to add the NetScaler IP if the HA pair is running in INC mode: 
https://github.com/citrix/citrix-k8s-ingress-controller/blob/master/deployment/baremetal/citrix-k8s-ingress-controller.yam

Is INC supported? (It is a requirement for Azure HA)l

**Comment by ankits123** [comment]
Hi Simon

Greetings of the Day and Happy new Year.
The ingress controller currently supports only HA in non INC mode.Can you please explain more on the use case and topology wrt. kubernetes clusters.
Are there multiple kubernetes clusters in different networks  that the HA pair needs to handle ?

**Comment by simongottschlag** [comment]
Hi and happy new year!

When running VPX in Azure, INC is required for HA.

**Comment by Saravanakumar2016** [comment]
HI @simongottschlag,

   Please consider the below solution for using CIC for Citrix HA INC mode on Azure cloud 

![image](https://user-images.githubusercontent.com/20974157/68109812-8442ad80-ff11-11e9-886d-14c58f767580.png)

Follow the below steps:
1) A new private ALB should be added to the resource group
2) A new private frontend IP on ALB should be used by CIC as NSIP
3) The backend IPs for ALB should be configured as the NSIPs of the HA INC pair
4) A health probe of TCP port 9000 should be instantiated on the load balancer

Once the setup is complete, CIC can access the Citrix ADC primary using the private ALB frontend IP

![image](https://user-images.githubusercontent.com/20974157/68110002-f74c2400-ff11-11e9-98dc-ab0b6c27ab3c.png)
**nsroot@Ubuntulogin:~$ ssh nsroot@172.20.0.6**
Password: 

> show ha node
1)     Node ID:      0 
       IP:      **172.20.0.5 (ns-vpx0)** 
       Node State: UP
       Master State: **Primary**
       Fail-Safe Mode: OFF
      
 Done
### > force ha failover
[WARNING]:Force Failover may cause configuration loss, peer health not optimum. Reason(s):
- HA heartbeats not seen on some interfaces
Please confirm whether you want force-failover (Y/N)? [N]:Y
 Done

Connection to 172.20.0.6 closed.

**nsroot@Ubuntulogin:~$ ssh nsroot@172.20.0.6**
Password: 
Last login: Thu Oct 31 08:43:31 2019 from 115.110.204.140

> show ha node
1)     Node ID:      0 
       IP:      **172.20.0.4 (ns-vpx1)** 
       Node State: UP
       Master State: ### Primary
       Fail-Safe Mode: OFF
