### ISSUE TITLE
Helm release installation failing if `entityPrefix` is a numeric value

### ISSUE THREAD

**Issue by marratj** [citrix/citrix-k8s-ingress-controller#401]
**Describe the bug**
The Helm chart is not explicitely quoting env var values in the Deployment template. This leads to the Helm release installation failing when one of the values is a purely numeric "string" (in our case `entityPrefix` -> `NS_APPS_NAME_PREFIX`)

**To Reproduce**
1. Steps
--> set `entityPrefix` to a purely numeric value during installation of the Helm release

2. Version of the Citrix Ingress Controller
--> 1.13.20

**Expected behavior**
The Deployment template in the Helm chart should explicitely use the `{{ quote .value }}` template function to circumvent this issue.

**Logs**
```
Release "netscaler" failed: Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found 1, error found in #10 byte of ...|,"value":14524697}],|..., bigger context ...|ue":"yes"},{"name":"NS_APPS_NAME_PREFIX","value":14524697}]
```

**Comment by priyankash-citrix** [comment]
This has been taken care in latest Helm chart release. Please let us know if you face any issues.
