### ISSUE TITLE
Certificates including the same DNS name causes massive log and command spam

### ISSUE THREAD

**Issue by lhw** [citrix/citrix-k8s-ingress-controller#411]
**Describe the bug**
When two ingresses managed by the same cic contain the same DNS names the cic will try to upload both and fail. It will retry after around 20ms. Causing millions of lines of log spam on kubernetes and on the ADC

**To Reproduce**
1. Create two ingresses with the same DNS name in the tls certificate
2. Notice massive log spam
3. Goto #410

**Expected behavior**
Just ignore or send an error.

**Logs**
kubectl logs https://gist.github.com/lhw/642a5e0ccd9f3082884f2944f303307e

**Additional context**
Same as other issues.

**Comment by ankits123** [comment]
@lhw  Thanks for the logs . We are going through it and update on RCA.
