### ISSUE TITLE
Errors in CRD syntax causes major log and command spam

### ISSUE THREAD

**Issue by lhw** [citrix/citrix-k8s-ingress-controller#412]
**Describe the bug**
In case a CRD (i.e. Rewrite) is deployed with a mistake the cic will retry the resource every 10-20ms.

**To Reproduce**
1. Deploy CRD with invalid rule content
2. Log/Command spam
3. Goto #410 

**Expected behavior**
Not that

**Logs**
kubectl logs https://gist.github.com/lhw/451afcb0db413026d2c31df48a2d7dff

**Additional context**
Same as the others

**Comment by RaveendraHolla** [comment]
Hi,

status updates causes this issue. A failure, followed by a status update back to CRD and further updates. We reproduced this issue. Will fix it in the coming release. One possible Work-around is to revoke permissions on "rewritepolicies/status". This will not allow CIC to update the status and then it will stop recursive calls.
