### ISSUE TITLE
[Feature] Traffic Domain

### ISSUE THREAD

**Issue by chifu1234** [citrix/citrix-k8s-ingress-controller#417]
**Is your feature request related to a problem? Please describe.**
Currently we use traffic domain to split traffic between multiple customers, for our none k8s environments. We still have to split the traffic via traffic domain for each customer with citrix-k8s-ingress-controller. 

**Describe the solution you'd like**
A ENV Value which defines the Traffic Domain which should be used on the citrix adc. default should be 0.

**Comment by ankits123** [comment]
Hi @chifu1234 Traffic domain feature has been deprecated in ADC and no new enhancement are coming in that area .
We have support of admin partition in CIC.
