### ISSUE TITLE
NS_APPS_NAME_PREFIX is not working when we set prefix "k8s" for two VIPs, need to fix

### ISSUE THREAD

**Issue by kanhpatel** [citrix/citrix-k8s-ingress-controller#437]
Hi Citrix Team,

I tested Workload VIP prefix “k8s” on two clusters but getting some weird behavior, when I apply ingress and ipam for a cluster it works and when applied the same prefix on other cluster VIP with name prefix “k8s”, the previous cluster VIP got deleted automatically. We tried to use the latest IPAM and Ingress docker image to citrix-k8s-ingress-controller:1.15.12 & citrix-ipam-controller:1.0.3, but still getting the same issue. So for investigation, I checked the log with the Netscaler LB team, they found our service account is deleting the VIP, seems like an issue with the VIP automation script, could you please help on this.

**Our requirement is to use "k8s" as the prefix for all VIP into the same Netscaler LoadBalanacer** 

**I am following the doc-https://raw.githubusercontent.com/citrix/citrix-k8s-ingress-controller/master/deployment/baremetal/citrix-k8s-ingress-controller.yaml**

**Some logs from LB:**
Jun 17 10:20:24 <local0.info> **X.X.X.X** 06/17/2021:10:20:24 GMT LB-XXXX 0-PPE-2 : default API CMD_EXECUTED 163322271 0 :  User s-pks-netscaler - Remote_ip **X.X.X.X**  - Command "show cs vserver k8s-runwaydev-traefik_80_kube-system_svc" - Status "Success" 
Jun 17 10:20:24 <local0.info> **X.X.X.X** 06/17/2021:10:20:24 GMT LB-XXXX 0-PPE-2 : default API CMD_EXECUTED 163322273 0 :  User s-pks-netscaler - Remote_ip **X.X.X.X**  - Command "show cs vserver k8s-runwaydev-traefik_80_kube-system_svc" - Status "Success" 
Jun 17 10:20:24 <local0.info> **X.X.X.X** 06/17/2021:10:20:24 GMT LB-XXXX 0-PPE-2 : default API CMD_EXECUTED 163322275 0 :  User s-pks-netscaler - Remote_ip **X.X.X.X** - Command "show cs vserver k8s-runwaydev-traefik_80_kube-system_svc" - Status "Success" 
Jun 17 10:20:24 <local0.info> **X.X.X.X** 06/17/2021:10:20:24 GMT LB-XXXX 0-PPE-2 : default API CMD_EXECUTED 163322278 0 :  User s-pks-netscaler - Remote_ip **X.X.X.X**  - Command "unbind cs vserver k8s-runwaydev-traefik_80_kube-system_svc -lbvserver default_lb" - Status "Success" 
**Jun 17 10:20:24 <local0.info> **X.X.X.X** 06/17/2021:10:20:24 GMT LB-XXXX 0-PPE-2 : default API CMD_EXECUTED 163322300 0 :  User s-pks-netscaler - Remote_ip **X.X.X.X** - Command "rm cs vserver k8s-runwaydev-traefik_80_kube-system_svc" - Status "Success"** 
Jun 17 10:20:31 <local0.info> **X.X.X.X** 06/17/2021:10:20:31 GMT LB-XXXX 0-PPE-2 : default API CMD_EXECUTED 163322454 0 :  User adm-root - Remote_ip **X.X.X.X**  - Command "show cs vserver k8s-runwaydev-traefik_80_kube-system_svc" - Status "ERROR: No such resource" 
Jun 17 10:20:31 <local0.info> **X.X.X.X** 06/17/2021:10:20:31 GMT LB-XXXX 0-PPE-2 : default API CMD_EXECUTED 163322458 0 :  User adm-root - Remote_ip **X.X.X.X** - Command "show cs vserver k8s-runwaydev-traefik_80_kube-system_svc" - Status "ERROR: No such resource" 
Jun 17 10:20:59 <local0.info> **X.X.X.X** 06/17/2021:10:20:59 GMT LB-XXXX 0-PPE-2 : default CLI CMD_EXECUTED 163322953 0 :  User nsroot - Remote_ip **X.X.X.X**  - Command "show cs vserver k8s-runwaydev-traefik_80_kube-system_svc" - Status "ERROR: No such resource"

**Comment by ankits123** [comment]
Hi @kanhpatel ,
If i understand it correct the same ADC is front ending 2 kubernetes clusters and there are 2 CIC's configuring ADC invidually.
For such scenario we have given the NS_APPS_NAME_PREFIX and it should be unique(e.g k8s1 , k8s2) in case if there are multiple CIC's configuring the ADC so that they can uniquely identify which ingress they are managing.
If the use the same value for both the CIC's in  NS_APPS_NAME_PREFIX then there will be conflict leading misconfiguration as mentioned above.
Can we please give different values for NS_APPS_NAME_PREFIX  and see if the issue is resolved.

**Comment by kanhpatel** [comment]
Thank you so much Ankit for your prompt reply.

**Comment by kanhpatel** [comment]
We already use in form of k8s1 and k8s2, and it's working fine, but this time our requirement was to use the same k8s for all VIPs.

**Comment by ankits123** [comment]
Thanks @kanhpatel for the clarification but having unique prefix values is mandatory for the reason i mentioned above.
