### ISSUE TITLE
Hashicorp Vault integration

### ISSUE THREAD

**Issue by simongottschlag** [citrix/citrix-k8s-ingress-controller#5]
Hi,

We are using Hashicorp for both secrets and PKI. Kubernetes already has an authentication method in Vault.

Would it be possible to integrate with Vault for secrets and certificates?

**Comment by chiradeep** [comment]
Just to clarify:
- you want to store the secret (in this case the NetScaler password) in Vault
- you want to store the TLS certificates that are bound to the cs vserver in Vault?

**Comment by simongottschlag** [comment]
Hi!

A few examples:
* Use Vault to issue certificates and rotate them frequently (both server and client)
* Use Vault to issue username/password for things NetScaler use (monitors, ldap actions, oauth actions etc)
* Use the Azure Secret engine to issue credentials used by NetScaler to connect to Azure

These are just a few.

**Comment by simongottschlag** [comment]
Hi,

In the ingress case It would be great to get certs that way, as well as credentials for ADCs(?)

**Comment by chiradeep** [comment]
Is the ADC a VPX/MPX or a CPX?

**Comment by simongottschlag** [comment]
Was thinking both, but we are using VPX/MPX

**Comment by pankajharnandka** [comment]
Simon we are planning to integrate with vaults in both traditional departments as well as k8s in future. Currently plan is to integrate with Hashicorp and keywhiz for getting certs and keys from remote vaults and keep in memory. In future, we will work on automating certs rotation by using vaults/secret discover services.

**Comment by chiradeep** [comment]
The TLS Kubernetes secret specified in the ingress resource gets copied to the ADC as an SSL certificate. So, you have to get your Vault secrets converted to Kubernetes secrets. There is a project here: https://github.com/Boostport/kubernetes-vault which can do that. Of course if the secret changes (rotates), the ingress controller will not update it in the ADC

**Comment by simongottschlag** [comment]
Ok! Thanks :) Looking forward to seeing this.

**Comment by chiradeep** [comment]
I believe this is fixed
https://developer-docs.citrix.com/projects/citrix-k8s-ingress-controller/en/latest/certificate-management/vault/
