### ISSUE TITLE
IPAM controller not assigning IP addresses

### ISSUE THREAD

**Issue by hashildy** [citrix/citrix-k8s-ingress-controller#512]
Nothing in the logs to indicate that there is an issue, however, when changing a service to type 'Load Balancer', the External-IP sits at 'Pending' status and never changes. If I manually set an IP address in the service definition, then it will create the config on my tier1 ADC with the provided IP address. However, I want to deploy the IPAM controller so that IP addresses are allocated automatically from the range(s) specified. 

Log files from ipam controller: 
INFO:root:VIP range configured as: ["172.16.50.160/28"]
DEBUG:kubernetes.client.rest:response body: {"apiVersion":"citrix.com/v1","items":[],"kind":"vipList","metadata":{"continue":"","resourceVersion":"11434509"}}

Ipam pod: 
Name:         citrix-k8s-ingress-ipam-76f46d46f4-k47fm
Namespace:    citrix
Priority:     0
Node:         ld-ubuntu3/172.16.50.106
Start Time:   Thu, 27 Jan 2022 19:23:18 +0000
Labels:       app=ipam
              app.kubernetes.io/instance=citrix-k8s-ingress
              app.kubernetes.io/name=ipam
              pod-template-hash=76f46d46f4
Annotations:  cni.projectcalico.org/containerID: e24a3096fe231a78f17fe0d0b35764a2202fd7882edd5d2dc6d427d4db3d23fb
              cni.projectcalico.org/podIP: 192.168.85.182/32
              cni.projectcalico.org/podIPs: 192.168.85.182/32
Status:       Running
IP:           192.168.85.182
IPs:
  IP:           192.168.85.182
Controlled By:  ReplicaSet/citrix-k8s-ingress-ipam-76f46d46f4
Containers:
  ipam:
    Container ID:   docker://72ed9535b8fcdd4a706942430469e36d66a829aab7b5290039c8b19cd0606540
    Image:          quay.io/citrix/citrix-ipam-controller:0.0.1
    Image ID:       docker-pullable://quay.io/citrix/citrix-ipam-controller@sha256:ee8cc760cec43c2d91f21e3018597e318d885ea5c0344c9c771992f12598bb08
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Thu, 27 Jan 2022 19:23:19 +0000
    Ready:          True
    Restart Count:  0
    Environment:
      VIP_RANGE:  ["172.16.50.160/28"]
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-s8gfq (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  kube-api-access-s8gfq:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  21m   default-scheduler  Successfully assigned citrix/citrix-k8s-ingress-ipam-76f46d46f4-k47fm to ld-ubuntu3
  Normal  Pulled     21m   kubelet            Container image "quay.io/citrix/citrix-ipam-controller:0.0.1" already present on machine
  Normal  Created    21m   kubelet            Created container ipam
  Normal  Started    21m   kubelet            Started container ipam

**Comment by apoorva-05** [comment]
@hashildy, how was the Citrix IPAM and Ingress Controller deployed, via the YAML manifests or helm charts?
1. If deployed manually using Yaml files can you update the IPAM image to the latest tag ```quay.io/citrix/citrix-ipam-controller:1.0.3```.
2. what is the output of the command ``` kubectl get vips --all-namespaces```. (This CRD is used by the IPAM controller and Ingress Controller to assign an IP to the service and then use that IP to configure the ADC)

**Comment by hashildy** [comment]
Hi @apoorva-05 - thanks for the quick reply. I had actually deployed this using helm charts in conjunction with a yaml file for providing unique configuration details. The version I was deploying for the IPAM controller was 0.0.1 so I updated that to use version 1.0.3, however, I am still unable to get an IP address allocated from the IPAM controller. 

The output of the command is: "No resources found"

I can confirm that the CRD exists by running a kubectl get crd with the following output: 
apigatewaypolicies.citrix.com                         2022-02-01T23:03:06Z
authpolicies.citrix.com                               2022-02-01T23:03:06Z
bots.citrix.com                                       2022-02-01T23:03:06Z
continuousdeployments.citrix.com                      2022-02-01T23:03:06Z
corspolicies.citrix.com                               2022-02-01T23:03:06Z
httproutes.citrix.com                                 2022-02-01T23:03:06Z
listeners.citrix.com                                  2022-02-01T23:03:06Z
ratelimits.citrix.com                                 2022-02-01T23:03:06Z
rewritepolicies.citrix.com                            2022-02-01T23:03:06Z
vips.citrix.com                                       2022-02-01T23:03:06Z
wafs.citrix.com                                       2022-02-01T23:03:06Z

Please advise if there is anything else you would like me to try. Thanks in advance for your assistance!

**Comment by apoorva-05** [comment]
@hashildy,
Is the Citrix ingress controller(CIC) deployed along with the Citrix IPAM controller? These work in conjunction to get the IP assigned to TypeLB k8s service.
If it's also deployed, can you share the values.yaml file used to deploy the Citrix Ingress controller and the service manifest YAML file used.

**Comment by hashildy** [comment]
Hi @apoorva-05 -- yes, CIC is also deployed alongside the Citrix IPAM controller. Here is the values file I used during the deploy: 

cic:
  enabled: true
  nsPort: 443
  nsProtocol: HTTPS
  ipam: true
  nsIP: 172.16.50.50
  adcCredentialSecret: adc-creds
  entityPrefix: k8s
  image: 'quay.io/citrix/citrix-k8s-ingress-controller:1.11.3'
  pullPolicy: IfNotPresent
  license:
    accept: 'Yes'
  logLevel: INFO
  nodeWatch: true
  crds:
    install: true
  ingressClass: []
  serviceClass: []
cpx:
  enabled: true
  image: 'quay.io/citrix/citrix-k8s-cpx-ingress:13.0-64.35'
  pullPolicy: IfNotPresent
  serviceType:
    loadBalancer:
      enabled: true
  cic:
    required: true
    image: 'quay.io/citrix/citrix-k8s-ingress-controller:1.11.3'
    pullPolicy: IfNotPresent
  license:
    accept: 'Yes'
  entityPrefix: k8s
  logLevel: INFO
  ADMSettings:
    licenseServerPort: 27000
  ingressClass: []
ipam:
  enabled: true
  image: 'quay.io/citrix/citrix-ipam-controller:1.0.3'
  pullPolicy: IfNotPresent
  vipRange: '["172.16.50.160/28"]'


And the service manifest file for the citric k8s ingress service:

apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: citrix-k8s-ingress
    meta.helm.sh/release-namespace: citrix
  creationTimestamp: "2022-02-01T23:03:06Z"
  labels:
    app: cpx-service
    app.kubernetes.io/managed-by: Helm
    service-type: citrix-k8s-ingress-citrix-adc-cpx-svcmon
  name: citrix-k8s-ingress-cpx-service
  namespace: citrix
  resourceVersion: "12937657"
  uid: fafce54c-7f6b-4c98-94f2-c1bd880e01b5
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.108.132.16
  clusterIPs:
  - 10.108.132.16
  externalTrafficPolicy: Local
  healthCheckNodePort: 31148
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 31549
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 31201
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: citrix-k8s-ingress-cpx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}

**Comment by apoorva-05** [comment]
@hashildy Will, you be able to update the Citrix Ingress Controller and the helm-charts to the latest?
You are currently using 1.11.3, it's been more than a year since this release. There have been quite a few bug fixes and enhancements that went around the area of IPAM.

**Comment by hashildy** [comment]
Thank you @apoorva-05 -- using the latest version worked! Thanks so much for your assistance. 
Can you please let me know if there is a way to reference the latest image without having to look up what that version is? Maybe an image tag? Thanks again fro your help.

**Comment by apoorva-05** [comment]
@hashildy "latest" tag like ```quay.io/citrix/citrix-k8s-ingress-controller:latest``` and ```quay.io/citrix/citrix-ipam-controller:latest``` will always point to the latest release,  does that help you?

**Comment by hashildy** [comment]
That is perfect @apoorva-05 ! Thanks so much for all of your help on this. Closing this issue now.
