### ISSUE TITLE
HTTPRoute CRD, for redirect action type the response status code must be in the range 300-399

### ISSUE THREAD

**Issue by progS1m** [citrix/citrix-k8s-ingress-controller#548]
**Describe the bug**
I noticed in the HTTPRoute CRD for redirects has this validation:
minimum: 100
maximum: 599

https://github.com/citrix/citrix-k8s-ingress-controller/blob/master/crd/contentrouting/HTTPRoute.yaml

Problem, when configuring a 404 this leads to an error and would either not work. See printscreen.

**Expected behavior**
Should be set to 
minimum: 300
maximum: 399

**Additional context**
GUI Error shows that redirects only supports values from 300-399:
<img width="940" alt="image" src="https://user-images.githubusercontent.com/9198744/180780776-95febbf6-a841-4c18-8f76-7041062071f4.png">

**Comment by progS1m** [comment]
I know for 404 Responder the workaround is to use a Rewrite-Responder: https://github.com/citrix/citrix-k8s-ingress-controller/blob/master/docs/crds/rewrite-responder.md

**Comment by aroraharsh23** [comment]
@progS1m Thanks for reporting, will review and correct the same.

**Comment by bharthi-m** [comment]
<img width="1449" alt="httproute" src="https://user-images.githubusercontent.com/82507334/200744721-8458f7b3-4f44-46f9-b2e6-bd05d503acb6.png">
The range has been updated in the latest version of Netscaler.

**Comment by ankits123** [comment]
closing the issue
