### ISSUE TITLE
Allow the HTTP method PATCH to be part of Authentication and Authorization policies' method list

### ISSUE THREAD

**Issue by enov** [citrix/citrix-k8s-ingress-controller#555]
**Is your feature request related to a problem? Please describe.**
The list of allowed methods for Authentication and Authorization policies does not allow PATCH. PATCH is a common HTTP method/verb to build RESTful APIs around.

**Describe the solution you'd like**
Add PATCH to the list of allowed methods for Authentication and Authorization policies and make it work.

**Describe alternatives you've considered**
n/a

**Additional context**
[`method` attribute for Authentication Policies](https://github.com/citrix/citrix-k8s-ingress-controller/blob/master/docs/crds/auth.md?plain=1#L153) only allows GET, POST, PUT and DELETE but not PATCH.
[`method` attribute for Authorization Policies](https://github.com/citrix/citrix-k8s-ingress-controller/blob/master/docs/crds/auth.md?plain=1#L179) only allows GET, POST, PUT and DELETE but not PATCH.

**Comment by subashd** [comment]
@enov 
CIC now supports PATCH in authentication and authorisations.
Please refer https://github.com/citrix/citrix-k8s-ingress-controller/releases/tag/1.33.4 for more details.

**Comment by enov** [comment]
Perfect, thanks!
