### ISSUE TITLE
Specify Traffic Domain?

### ISSUE THREAD

**Issue by alburg** [citrix/citrix-k8s-ingress-controller#6]
Hi - is it possible to specify a non-default traffic domain in the pod?

**Comment by janraj** [comment]
@alburg, I am not clear about the question. Are you looking for traffic domain support on  Citrix ADC via Citrix Ingress controller? If yes, Citrix ingress controller supports partition. Use partition username and password for bringing up Citrix Ingress Controller.

**Comment by alburg** [comment]
Thank you for the response @janraj and my apologies for not being clear.  Our ADC currently has one partition and two traffic domains.  The Citrix Ingress Controller is using the default traffic domain.  I'd like it to use the other domain.  Is there a way I can bring it up and tell it to use the other domain?  Or is a partition my best bet?

**Comment by janraj** [comment]
@alburg, Traffic domain is not supported but Partition is supported. You have to rely on the partition for your requirement.

**Comment by alburg** [comment]
Thank you @janraj , I was able to get this working successfully with a Partition.  Thanks!
