### ISSUE TITLE
Preconfigured Certificate Example Syntax

### ISSUE THREAD

**Issue by alburg** [citrix/citrix-k8s-ingress-controller#8]
Hi - it looks like the syntax on the preconfigured certificates example on the tls-certificate-handling.md page is incorrect.

I could not get this to work:
`'ingress.citrix.com/preconfigured-certkey : '{"certs": [ {"name": <name>, ["type": "default|sni|ca"]} ] }'`

I could get this to work:
`ingress.citrix.com/preconfigured-certkey : '{"certs": [ {"name": "<name>", "type": "default|sni|ca"} ] }'`

(I removed the single quote at the top of the string, added double quotes to the cert name, and removed the brackets around the type)

**Comment by janraj** [comment]
@alburg, Thanks for your feedback. Its a documentation bug  (.md format has caused this) from our side. We will fix this. As you know annotations start without any quotes.    We have a slack channel through which you can directly reach out to the development community in case any help is required.

**Comment by nirmalkn** [comment]
Hi @alburg, i have updated the syntax as suggested. The updated  tls-certificate-handling.md page is now available.

**Comment by alburg** [comment]
Thanks!
