### ISSUE TITLE
After upgrade VIP naming in 1.2.0, VIPs can't be applied due to existence of old VIP names

### ISSUE THREAD

**Issue by IKabdyushev** [citrix/citrix-k8s-ingress-controller#81]
Hello!
We had VIPs created via Citrix Ingress Contoller, the created name format was: `PREFIX-VIP:PORT:PROTOCOL`.
1) In versions prior to 1.2.0 PREFIX could have **non** alphanumeric characters (- or _). We used these characters
2) In new versions the name format was changed: `PREFIX-VIP:PORT:PROTOCOL` changed to `PREFIX-VIP_PORT_PROTOCOL` (: changed _)

Summarizing these two problems, the old VIPs couldn't be updated using new cic version (1.2.0) as old VIPs with old names are still exist. We can change PREFIX to match alphanumeric in old version (update VIPs prefix in name), as there is env: `NS_APPS_NAME_PREFIX`. After this update to new (1.2.0) version. But, we can't choose delimiter for VIP naming, therefore we should **entirely** delete VIPs using old cic version, and then create them using new version (1.2.0).
Could you introduce new env to choose delimiter, for us not to delete all ingress created before, or any other solution?

**Comment by krdpk17** [comment]
@IKabdyushev thanks for reporting this. Wished to know about prefix name which is used by you.

**Comment by krdpk17** [comment]
@IKabdyushev In 1.2.0, delimiter is added by default and it is '-'.
So, as an example, If  NS_APPS_NAME_PREFIX is '**abc**-' in previous release, then in 1.2.0, its value should be '**abc**' . '-' will be added by default. 

In 1.2.0, non-alphanumeric characters are not allowed.

**Comment by IKabdyushev** [comment]
@krdpk17 Prefix is not a problem as it is changeable.
When I looked at logs of cic, i noticed that
`PREFIX-VIP:PORT:PROTOCOL changed to PREFIX-VIP_PORT_PROTOCOL (: changed _)`
That's why even if I change Prefix, I can't change the delimiter : to _ as cic names VIP automatically. 

We had VIP something like
`TEST_k8s-192.168.1.1:443:ssl`
Ok, now the prefix is only alphanumeric, suppose we change it to simple k8s so result is
`k8s-192.168.1.1:443:ssl`
THen update the CIC version to 1.2.0. But after upgrade cic tries to create 
`k8s-192.168.1.1_443_ssl` 
where : is changed to _, which cause an error to occur (VIP already exists)

**Comment by krdpk17** [comment]
@IKabdyushev thanks for the info. 
<<That's why even if I change Prefix, I can't change the delimiter : to _ as cic names VIP automatically.>>
New CIC (1.2.0) should automatically take care of changing from  k8s-192.168.1.1:443:ssl to k8s-192.168.1.1_443_ssl

Wished to check if we can have a remote session for this. Kindly suggest.

**Comment by krdpk17** [comment]
@IKabdyushev Greetings of the day. Wished to check if we can have meeting this week whenever convenient for you.

@ankits123 @janraj @haroraCitrix

**Comment by IKabdyushev** [comment]
@krdpk17 Hello, let's have a call tomorrow (31 July) 3pm our local time (GMT+6).

**Comment by krdpk17** [comment]
@IKabdyushev thanks for suggestion. It will be 2:30 PM(afternoon) India time (IST). Kindly share the mail ID on which we can send you the GTM meeting  invite.
@ankits123 @janraj @haroraCitrix

**Comment by krdpk17** [comment]
@IKabdyushev

**Comment by krdpk17** [comment]
@IKabdyushev Good morning. I didn't see any mail from your side. So, wished to check with you.
Alternately, we can share the GTM session link here, if it is fine to you. Kindly suggest.
@ankits123 @janraj @haroraCitrix

**Comment by IKabdyushev** [comment]
@krdpk17 Hello! Sorry for not replying, we solved the problem manually, so no call is needed anymore. we provide some information about it later in this issue and then close it.

**Comment by krdpk17** [comment]
@IKabdyushev thanks for the info. Good to know this.

**Comment by krdpk17** [comment]
Closing as user has resolved the issue.
