### ISSUE TITLE
Install citrix-k8s-ingress-controller with helm in non-default namespace failed

### ISSUE THREAD

**Issue by LipingMao** [citrix/citrix-k8s-ingress-controller#9]
Helm charts hard-code install serviceaccount in default namespace, when I install it in non-default namespace(it is cpx in my env), it will failed.

Here is command to install helm:
helm install citrix-k8s-cpx-ingress-controller --namespace cpx --name limao-cpx --set license.accept=yes,ingressClass[0]=cpx

Here is the log:
  Warning  FailedCreate  49s (x15 over 2m11s)  replicaset-controller  Error creating: pods "cpx-ingress-86b74c8965-" is forbidden: error looking up service account cpx/cpx-ingress-k8-role: serviceaccount "cpx-ingress-k8-role" not found

It works if I install in default namespaces.

**Comment by priyankash-citrix** [comment]
@LipingMao We have updated our helm charts. Now you should be able to deploy pods in a non-default namespace using helm charts.

**Comment by LipingMao** [comment]
@priyankash-citrix  thanks, works for me.
