### ISSUE TITLE
Experiencing VPX issues - VIP Naming and HA Configuration Not Saving on Update

### ISSUE THREAD

**Issue by travissutton** [citrix/citrix-k8s-ingress-controller#94]
**Describe the bug**
I'm running into 2 issues with my deployment. Overall, the solution works but it's just behaving a bit odd. I've also requested an invite to the slack channel, but have not received anything back. I'd be happy to discuss more there if needed.

First, all VIPs created in the VPX are duplicated for the name: `vip_name_svc_vip_name_svc`. It might be related to the CS VIP name, but since they are the same it's difficult to tell. The CS VIP is correct, but the load balancing virtual server is duplicated. Examples below. 

Second, I'm running in HA mode and I've noticed that updates to the configuration are not saved. This seems to be every time a change is made. I've had to manually go back in and save the configuration. When I've checked the difference it is the VIPs created by service changes.

**To Reproduce**
1. Steps

  - Create `LoadBalancer` type services, check names under Traffic Management > Load Balancing > Virtual Servers
  - While running a HA configuration, confirm configuration is saved/synced, create a `LoadBalancer` service and check to see if configuration is saved after VIPs are created.

2. Version of the Citrix Ingress Controller
  `1.2.0`
3. Version of MPX/VPX/CPX
VPX: `12.1 51.19` - Running in HA Pair
4. Environment variables (minus secrets)
```
Args:
      --ingress-class citrix
      --feature-node-watch true
      --ipam=citrix-ipam-controller
    Environment:
      NS_IP:                x.x.x.x
      NS_USER:              <set to the key 'username' in secret 'xxxxns-login'>  Optional: false
      NS_PASSWORD:          <set to the key 'password' in secret 'xxxxns-login'>  Optional: false
      EULA:                 true
      LOGLEVEL:             DEBUG
      NS_PROTOCOL:          HTTPS
      NS_PORT:              443
      NS_APPS_NAME_PREFIX:  xxxxk8s
```
**Expected behavior**

```
# Examples for Duplicated Names

## Content Vservers
xxxxk8s-xxxxmq-rabbitmq-svc_default_15672_svc
xxxxk8s-xxxxmq-rabbitmq-svc_default_4369_svc

## Vservers
xxxxk8s-xxxxmq-rabbitmq-svc_default_15672_svc_xxxxk8s-xxxxmq-rabbitmq-svc_default_15672_svc
xxxxk8s-xxxxmq-rabbitmq-svc_default_4369_svc_xxxxk8s-xxxxmq-rabbitmq-svc_default_4369_svc
```

If the Vserver name duplication is expected that ultimately will just get messy. I understand it might be using the service name/options to create a naming schema, but once it creates the CS VIP, it seems like it can use the same name and simply add `_vserver` or something as a suffix to keep the names different. Duplicating such a long name is a struggle to go through at times and definitely makes mapping back/forth tough.

For the config save, I would expect this solution to be saving configuration on the HA setup. It's definitely a risk for that not to be happening.

**Logs**
kubectl logs

**Additional context**

**Comment by verzunof** [comment]
Travis,
The naming convention, generally is <prefix>_<entity_name>_<namespace>_<destination>.
Formation of entity_name and destination may be different for different cases.
For services destination is the same as entity because there is no real content switching, so, the first and second parts become the same.
We treated entity names creation as something internal with only requirement of avoiding clashes.
Do you see this convention as a problem?

Currently we do not do saveconfig. Configuration is propagated to the secondary, in case of failover systems will continue to work.

**Comment by travissutton** [comment]
@verunof, overall I like the way you name them if you look at just the CS virtual server. Unfortunately, by the time you get to the 2nd layer you can get close to the 127 character limit. This leaves 63 characters before duplication. You'll lose 8 from this because `svc_` and `_svc` are both used. When you factor in the namespace (which `default` is probably a shorter one) and port, you are left with sub-40 characters for naming.

Beyond that, in our case, we monitor dynamically our VIPs and extremely long names are tough on alerts. Also it could make it difficult to know if it was the CS VIP or the LB VIP having the issue. This is just my opinion, but if we had the same name: `xxxxk8s-xxxxmq-rabbitmq-svc_default_15672_svc` but instead landed on these VIP names:

  - `xxxxk8s-xxxxmq-rabbitmq-svc_default_15672_svc_cs-vip`
  - `xxxxk8s-xxxxmq-rabbitmq-svc_default_15672_svc_lb-vip`

Something like that keeps them shorter and identifiable but unique between the vservers.


Regarding the configuration save, is there a reason you don't save? It shows up as a diff and while it's copied between the HA systems the config still wouldn't persist an issue. Maybe we're trained to not have configs unsaved, but seeing that flag all the time is annoying. You may have a reason for it with the k8s deployment, but now we'd never know when it was real or not. There could be real configuration items not being saved and users might ignore the flag because it's always there in a constantly shifting k8s environment.

**Comment by bhardwajk** [comment]
@travissutton you've been invited to our slack workspace  https://citrixadccloudnative.slack.com on tr****@l*****7.com.

**Comment by janraj** [comment]
@travissutton,  Please find my answer to your queries.
Issue 1) Repetition and longer name for entities.   
               We will optimize this further.  We had to take such naming as Citrix Node Controller always makes sure the desired state of Kubernetes available in Citrix ADC without having any cache at Citrix Ingress controller.  We could make Citrix Ingress Controller is stateless because of such a naming convention. We understood your point. We will do further optimization for improving user convenience. 
Issue 2) Save Config:
                Save config is CPU intense.  In kubernetes POD's are having dynamic nature and it can change the IP at any time. We get such large events and we don't want to make save config call for every such event. However, Citrix Ingress Controller makes sure Citrix ADC has the correct state of Kubernetes.

**Comment by ankits123** [comment]
We have optimized the naming convention keeping in mind to support large k8s entity names.
Please refer the latest CIC release.
The saveconfig behavior has already been clarified above . For k8s since desired state is in kubernetes so saveconfig don't much sense.
